// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/rifaulkner/sports-kernel/api/sk-serve/contract"
)

type CapUtilizationSummary struct {
	CapUtilization int `json:"capUtilization"`
	NumContracts   int `json:"numContracts"`
}

type ContractRestructureInput struct {
	ContractID                 string               `json:"contractId"`
	ContractRestructureDetails []*ContractYearInput `json:"contractRestructureDetails"`
}

type ContractYear struct {
	Year             int `json:"year"`
	TotalAmount      int `json:"totalAmount"`
	PaidAmount       int `json:"paidAmount"`
	GuaranteedAmount int `json:"guaranteedAmount"`
}

type ContractYearInput struct {
	Year             int `json:"year"`
	TotalAmount      int `json:"totalAmount"`
	PaidAmount       int `json:"paidAmount"`
	GuaranteedAmount int `json:"guaranteedAmount"`
}

type ContractsMetadata struct {
	TotalUtilizedCap  int                    `json:"totalUtilizedCap"`
	TotalAvailableCap int                    `json:"totalAvailableCap"`
	QbUtilizedCap     *CapUtilizationSummary `json:"qbUtilizedCap"`
	RbUtilizedCap     *CapUtilizationSummary `json:"rbUtilizedCap"`
	WrUtilizedCap     *CapUtilizationSummary `json:"wrUtilizedCap"`
	TeUtilizedCap     *CapUtilizationSummary `json:"teUtilizedCap"`
}

type DeadCap struct {
	AssociatedContractID string             `json:"associatedContractId"`
	Amount               int                `json:"amount"`
	Contract             *contract.Contract `json:"contract"`
}

type DeadCapYear struct {
	Year           int        `json:"year"`
	DeadCapAccrued []*DeadCap `json:"deadCapAccrued"`
}

type Division struct {
	DivisionName string `json:"divisionName"`
	LeadingWins  *int   `json:"leadingWins"`
}

type DraftPick struct {
	Round           int     `json:"round"`
	Value           *int    `json:"value"`
	OriginalOwnerID *string `json:"originalOwnerId"`
}

type DraftYear struct {
	Year  int          `json:"year"`
	Picks []*DraftPick `json:"picks"`
}

type League struct {
	ID         string      `json:"id"`
	LeagueName string      `json:"leagueName"`
	LogoURL    string      `json:"logoUrl"`
	StartDate  time.Time   `json:"startDate"`
	Teams      []*Team     `json:"teams"`
	Divisions  []*Division `json:"divisions"`
}

type LeaguePost struct {
	ID       string         `json:"id"`
	Author   string         `json:"author"`
	Title    string         `json:"title"`
	PostDate time.Time      `json:"postDate"`
	Content  string         `json:"content"`
	Comments []*PostComment `json:"comments"`
}

type NewLeaguePost struct {
	Author  string `json:"author"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type NewPlayerNfl struct {
	PlayerName   string  `json:"playerName"`
	Position     string  `json:"position"`
	PositionRank *int    `json:"positionRank"`
	TeamNfl      *string `json:"teamNFL"`
	Birthday     *string `json:"birthday"`
	Avatar       *string `json:"avatar"`
	OverallRank  *int    `json:"overallRank"`
}

type NewPostComment struct {
	Author  string `json:"author"`
	Content string `json:"content"`
}

type NewTeam struct {
	ID          string     `json:"id"`
	TeamName    string     `json:"teamName"`
	Division    *string    `json:"division"`
	FoundedDate *time.Time `json:"foundedDate"`
}

type NewUser struct {
	OwnerName string `json:"ownerName"`
	Email     string `json:"email"`
	Avatar    string `json:"avatar"`
}

type NewUserRole struct {
	UserID string `json:"userId"`
	Role   string `json:"role"`
}

type PlayerNfl struct {
	ID           string `json:"id"`
	OverallRank  int    `json:"overallRank"`
	PlayerName   string `json:"playerName"`
	Position     string `json:"position"`
	PositionRank int    `json:"positionRank"`
	TeamNfl      string `json:"teamNFL"`
	Birthday     string `json:"birthday"`
	Avatar       string `json:"avatar"`
}

type PostComment struct {
	ID          string    `json:"id"`
	Author      string    `json:"author"`
	Content     string    `json:"content"`
	CommentDate time.Time `json:"commentDate"`
}

type Team struct {
	ID                       string               `json:"id"`
	FoundedDate              time.Time            `json:"foundedDate"`
	TeamName                 string               `json:"teamName"`
	OwnerID                  string               `json:"ownerID"`
	Division                 *string              `json:"division"`
	CurrentContractsMetadata *ContractsMetadata   `json:"currentContractsMetadata"`
	FutureContractsMetadata  []*ContractsMetadata `json:"futureContractsMetadata"`
	TeamAssets               *TeamAssets          `json:"teamAssets"`
	TeamLiabilities          *TeamLiabilities     `json:"teamLiabilities"`
}

type TeamAssets struct {
	DraftPicks []*DraftYear `json:"draftPicks"`
}

type TeamLiabilities struct {
	DeadCap []*DeadCapYear `json:"deadCap"`
}

type Transaction struct {
	TransactionType TransactionType `json:"transactionType"`
	OccurrenceDate  int             `json:"occurrenceDate"`
	TransactionData string          `json:"transactionData"`
}

type TransactionInput struct {
	TransactionType TransactionType `json:"transactionType"`
	TransactionData string          `json:"transactionData"`
}

type User struct {
	ID        string `json:"id"`
	OwnerName string `json:"ownerName"`
	Email     string `json:"email"`
	Avatar    string `json:"avatar"`
}

type UserPreferences struct {
	ID                string    `json:"id"`
	OwnerName         string    `json:"ownerName"`
	PreferredLeagueID *string   `json:"preferredLeagueId"`
	IsAdmin           *bool     `json:"isAdmin"`
	Leagues           []*League `json:"leagues"`
}

type UserRoles struct {
	ID     string `json:"id"`
	UserID string `json:"userId"`
	Role   string `json:"role"`
}

type ContractRestructureStatus string

const (
	ContractRestructureStatusEligible               ContractRestructureStatus = "ELIGIBLE"
	ContractRestructureStatusIneligibleFinalYear    ContractRestructureStatus = "INELIGIBLE_FINAL_YEAR"
	ContractRestructureStatusPreviouslyRestructured ContractRestructureStatus = "PREVIOUSLY_RESTRUCTURED"
)

var AllContractRestructureStatus = []ContractRestructureStatus{
	ContractRestructureStatusEligible,
	ContractRestructureStatusIneligibleFinalYear,
	ContractRestructureStatusPreviouslyRestructured,
}

func (e ContractRestructureStatus) IsValid() bool {
	switch e {
	case ContractRestructureStatusEligible, ContractRestructureStatusIneligibleFinalYear, ContractRestructureStatusPreviouslyRestructured:
		return true
	}
	return false
}

func (e ContractRestructureStatus) String() string {
	return string(e)
}

func (e *ContractRestructureStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ContractRestructureStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ContractRestructureStatus", str)
	}
	return nil
}

func (e ContractRestructureStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ContractStatus string

const (
	ContractStatusActive          ContractStatus = "ACTIVE"
	ContractStatusInactiveExpired ContractStatus = "INACTIVE_EXPIRED"
	ContractStatusInactiveDropped ContractStatus = "INACTIVE_DROPPED"
)

var AllContractStatus = []ContractStatus{
	ContractStatusActive,
	ContractStatusInactiveExpired,
	ContractStatusInactiveDropped,
}

func (e ContractStatus) IsValid() bool {
	switch e {
	case ContractStatusActive, ContractStatusInactiveExpired, ContractStatusInactiveDropped:
		return true
	}
	return false
}

func (e ContractStatus) String() string {
	return string(e)
}

func (e *ContractStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ContractStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ContractStatus", str)
	}
	return nil
}

func (e ContractStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Role string

const (
	RoleAdmin         Role = "ADMIN"
	RoleLeagueManager Role = "LEAGUE_MANAGER"
	RoleLeagueMember  Role = "LEAGUE_MEMBER"
	RoleTeamOwner     Role = "TEAM_OWNER"
)

var AllRole = []Role{
	RoleAdmin,
	RoleLeagueManager,
	RoleLeagueMember,
	RoleTeamOwner,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin, RoleLeagueManager, RoleLeagueMember, RoleTeamOwner:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type TransactionType string

const (
	TransactionTypeContractRestructure TransactionType = "CONTRACT_RESTRUCTURE"
)

var AllTransactionType = []TransactionType{
	TransactionTypeContractRestructure,
}

func (e TransactionType) IsValid() bool {
	switch e {
	case TransactionTypeContractRestructure:
		return true
	}
	return false
}

func (e TransactionType) String() string {
	return string(e)
}

func (e *TransactionType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TransactionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TransactionType", str)
	}
	return nil
}

func (e TransactionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
